"use server";

// Invoice server actions.
//   * createInvoice — writes invoice + items, calculates totals server-side.
//   * (Reads happen directly from server components via lib/invoice-data.ts.)

import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";

export interface InvoiceItemInput {
  description: string;
  unit_price: number;
}

export interface CreateInvoiceInput {
  ticket_id: string;
  customer_name: string;
  customer_address?: string | null;
  contact_no?: string | null;
  invoice_date?: string;                     // "YYYY-MM-DD"; defaults to today
  time_in?: string | null;
  time_out?: string | null;
  discount?: number;
  gst_amount?: number;
  deposit_amount?: number;
  notes?: string | null;
  items: InvoiceItemInput[];
}

function num(v: unknown): number {
  const n = typeof v === "number" ? v : parseFloat(String(v ?? "0"));
  return isFinite(n) ? Math.max(0, Math.round(n * 100) / 100) : 0;
}

export async function createInvoice(
  input: CreateInvoiceInput
): Promise<{ error?: string; id?: string; receipt_no?: string }> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "Not signed in." };

  const items = input.items
    .map((i) => ({ description: i.description.trim(), unit_price: num(i.unit_price) }))
    .filter((i) => i.description.length > 0);
  if (items.length === 0) return { error: "Add at least one line item." };
  if (!input.customer_name.trim()) return { error: "Customer name is required." };

  const discount = num(input.discount);
  const gst      = num(input.gst_amount);
  const deposit  = num(input.deposit_amount);

  const subtotal    = items.reduce((s, i) => s + i.unit_price, 0);
  const grand_total = Math.max(0, Math.round((subtotal - discount + gst - deposit) * 100) / 100);

  // Look up the estate + category for this ticket so we can stamp them on the
  // invoice. Lets the /admin/invoices category filter and sub-menus work.
  const { data: ticketMeta } = await supabase
    .from("tickets")
    .select("client_id, clients(category)")
    .eq("id", input.ticket_id)
    .maybeSingle<{ client_id: string; clients: { category: string } | null }>();

  // 1. Insert invoice header. Receipt number auto-generated by DB.
  const { data: inserted, error: invErr } = await supabase
    .from("invoices")
    .insert({
      ticket_id:        input.ticket_id,
      client_id:        ticketMeta?.client_id ?? null,
      category:         ticketMeta?.clients?.category ?? null,
      created_by:       user.id,
      customer_name:    input.customer_name.trim(),
      customer_address: input.customer_address?.trim() || null,
      contact_no:       input.contact_no?.trim() || null,
      invoice_date:     input.invoice_date || new Date().toISOString().slice(0, 10),
      time_in:          input.time_in?.trim() || null,
      time_out:         input.time_out?.trim() || null,
      subtotal,
      discount,
      gst_amount:       gst,
      deposit_amount:   deposit,
      grand_total,
      notes:            input.notes?.trim() || null,
    })
    .select("id, receipt_no")
    .single();

  if (invErr || !inserted) return { error: invErr?.message ?? "Insert failed." };

  // 2. Insert items.
  const rows = items.map((it, idx) => ({
    invoice_id: inserted.id,
    description: it.description,
    unit_price:  it.unit_price,
    sort_order:  idx,
  }));
  const { error: itemsErr } = await supabase.from("invoice_items").insert(rows);
  if (itemsErr) return { error: `Invoice saved but line items failed: ${itemsErr.message}` };

  revalidatePath(`/technician/jobs/${input.ticket_id}`);
  revalidatePath(`/admin/tickets/${input.ticket_id}`);
  revalidatePath(`/client/tickets/${input.ticket_id}`);
  return { id: inserted.id, receipt_no: inserted.receipt_no };
}

// ---------------------------------------------------------------------------
// Admin: manual invoice generation (no ticket).
// ---------------------------------------------------------------------------
export interface CreateManualInvoiceInput {
  customer_name: string;
  customer_address?: string | null;
  contact_no?: string | null;
  invoice_date?: string;
  time_in?: string | null;
  time_out?: string | null;
  category: string;                 // Retail | MCST | SBS
  client_id?: string | null;        // optional link to an estate
  discount?: number;
  gst_amount?: number;
  deposit_amount?: number;
  notes?: string | null;
  items: InvoiceItemInput[];
  before_photo_paths?: string[];
  after_photo_paths?: string[];
}

export async function createManualInvoice(
  input: CreateManualInvoiceInput
): Promise<{ error?: string; id?: string; receipt_no?: string; organization_id?: string }> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "Not signed in." };

  if (!input.customer_name?.trim()) return { error: "Customer name is required." };
  if (input.category !== "Retail" && input.category !== "MCST" && input.category !== "SBS") {
    return { error: "Pick a valid category (Retail / MCST / SBS)." };
  }

  const items = input.items
    .map((i) => ({ description: i.description.trim(), unit_price: num(i.unit_price) }))
    .filter((i) => i.description.length > 0);
  if (items.length === 0) return { error: "Add at least one line item." };

  const discount = num(input.discount);
  const gst      = num(input.gst_amount);
  const deposit  = num(input.deposit_amount);

  const subtotal    = items.reduce((s, i) => s + i.unit_price, 0);
  const grand_total = Math.max(0, Math.round((subtotal - discount + gst - deposit) * 100) / 100);

  const { data: inserted, error: invErr } = await supabase
    .from("invoices")
    .insert({
      ticket_id:        null,
      client_id:        input.client_id ?? null,
      category:         input.category,
      created_by:       user.id,
      customer_name:    input.customer_name.trim(),
      customer_address: input.customer_address?.trim() || null,
      contact_no:       input.contact_no?.trim() || null,
      invoice_date:     input.invoice_date || new Date().toISOString().slice(0, 10),
      time_in:          input.time_in?.trim() || null,
      time_out:         input.time_out?.trim() || null,
      subtotal,
      discount,
      gst_amount:       gst,
      deposit_amount:   deposit,
      grand_total,
      notes:            input.notes?.trim() || null,
      before_photo_paths: input.before_photo_paths ?? [],
      after_photo_paths:  input.after_photo_paths ?? [],
    })
    .select("id, receipt_no, organization_id")
    .single<{ id: string; receipt_no: string; organization_id: string }>();

  if (invErr || !inserted) return { error: invErr?.message ?? "Insert failed." };

  const rows = items.map((it, idx) => ({
    invoice_id:  inserted.id,
    description: it.description,
    unit_price:  it.unit_price,
    sort_order:  idx,
  }));
  const { error: itemsErr } = await supabase.from("invoice_items").insert(rows);
  if (itemsErr) return { error: `Invoice saved but line items failed: ${itemsErr.message}` };

  revalidatePath("/admin/invoices");
  return { id: inserted.id, receipt_no: inserted.receipt_no, organization_id: inserted.organization_id };
}

// ---------------------------------------------------------------------------
// Admin: toggle paid / unpaid.
// ---------------------------------------------------------------------------
export async function toggleInvoicePaid(
  invoiceId: string,
  isPaid: boolean
): Promise<{ error?: string }> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "Not signed in." };

  const { error } = await supabase
    .from("invoices")
    .update({
      is_paid: isPaid,
      paid_at: isPaid ? new Date().toISOString() : null,
      paid_by: isPaid ? user.id : null,
    })
    .eq("id", invoiceId);

  if (error) return { error: error.message };

  revalidatePath("/admin/invoices");
  return {};
}


// ---------------------------------------------------------------------------
// Update an existing invoice (edit flow — same PDF, updated fields).
// ---------------------------------------------------------------------------
export async function updateInvoice(
  invoiceId: string,
  input: CreateInvoiceInput
): Promise<{ error?: string; id?: string; receipt_no?: string }> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: "Not signed in." };

  const items = input.items
    .map((i) => ({ description: i.description.trim(), unit_price: num(i.unit_price) }))
    .filter((i) => i.description.length > 0);
  if (items.length === 0) return { error: "Add at least one line item." };
  if (!input.customer_name.trim()) return { error: "Customer name is required." };

  const discount = num(input.discount);
  const gst      = num(input.gst_amount);
  const deposit  = num(input.deposit_amount);
  const subtotal    = items.reduce((s, i) => s + i.unit_price, 0);
  const grand_total = Math.max(0, Math.round((subtotal - discount + gst - deposit) * 100) / 100);

  const { data: updated, error: upErr } = await supabase
    .from("invoices")
    .update({
      customer_name:    input.customer_name.trim(),
      customer_address: input.customer_address?.trim() || null,
      contact_no:       input.contact_no?.trim() || null,
      invoice_date:     input.invoice_date || new Date().toISOString().slice(0, 10),
      time_in:          input.time_in?.trim() || null,
      time_out:         input.time_out?.trim() || null,
      subtotal,
      discount,
      gst_amount:       gst,
      deposit_amount:   deposit,
      grand_total,
      notes:            input.notes?.trim() || null,
    })
    .eq("id", invoiceId)
    .select("id, receipt_no, ticket_id")
    .maybeSingle<{ id: string; receipt_no: string; ticket_id: string | null }>();

  if (upErr) return { error: upErr.message };
  if (!updated) return { error: "Not allowed to update this invoice, or it no longer exists." };

  await supabase.from("invoice_items").delete().eq("invoice_id", invoiceId);
  const rows = items.map((it, idx) => ({
    invoice_id: invoiceId,
    description: it.description,
    unit_price:  it.unit_price,
    sort_order:  idx,
  }));
  const { error: itemsErr } = await supabase.from("invoice_items").insert(rows);
  if (itemsErr) return { error: `Invoice saved but items failed: ${itemsErr.message}` };

  if (updated.ticket_id) {
    revalidatePath(`/technician/jobs/${updated.ticket_id}`);
    revalidatePath(`/admin/tickets/${updated.ticket_id}`);
    revalidatePath(`/client/tickets/${updated.ticket_id}`);
  }
  revalidatePath("/admin/invoices");
  return { id: updated.id, receipt_no: updated.receipt_no };
}


// ---------------------------------------------------------------------------
// Update an existing MANUAL invoice (ticket_id is null).
// Reuses createManualInvoice's shape.
// ---------------------------------------------------------------------------
export async function updateManualInvoice(
  invoiceId: string,
  input: CreateManualInvoiceInput
): Promise<{ error?: string; id?: string; receipt_no?: string; organization_id?: string }> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: "Not signed in." };

  if (!input.customer_name?.trim()) return { error: "Customer name is required." };
  if (input.category !== "Retail" && input.category !== "MCST" && input.category !== "SBS") {
    return { error: "Pick a valid category (Retail / MCST / SBS)." };
  }

  const items = input.items
    .map((i) => ({ description: i.description.trim(), unit_price: num(i.unit_price) }))
    .filter((i) => i.description.length > 0);
  if (items.length === 0) return { error: "Add at least one line item." };

  const discount = num(input.discount);
  const gst      = num(input.gst_amount);
  const deposit  = num(input.deposit_amount);
  const subtotal    = items.reduce((s, i) => s + i.unit_price, 0);
  const grand_total = Math.max(0, Math.round((subtotal - discount + gst - deposit) * 100) / 100);

  const { data: updated, error: upErr } = await supabase
    .from("invoices")
    .update({
      client_id:        input.client_id ?? null,
      category:         input.category,
      customer_name:    input.customer_name.trim(),
      customer_address: input.customer_address?.trim() || null,
      contact_no:       input.contact_no?.trim() || null,
      invoice_date:     input.invoice_date || new Date().toISOString().slice(0, 10),
      time_in:          input.time_in?.trim() || null,
      time_out:         input.time_out?.trim() || null,
      subtotal, discount, gst_amount: gst, deposit_amount: deposit, grand_total,
      notes:            input.notes?.trim() || null,
      before_photo_paths: input.before_photo_paths ?? [],
      after_photo_paths:  input.after_photo_paths ?? [],
    })
    .eq("id", invoiceId)
    .select("id, receipt_no, organization_id")
    .maybeSingle<{ id: string; receipt_no: string; organization_id: string }>();

  if (upErr) return { error: upErr.message };
  if (!updated) return { error: "Not allowed to update this invoice, or it no longer exists." };

  await supabase.from("invoice_items").delete().eq("invoice_id", invoiceId);
  const rows = items.map((it, idx) => ({
    invoice_id: invoiceId,
    description: it.description,
    unit_price:  it.unit_price,
    sort_order:  idx,
  }));
  const { error: itemsErr } = await supabase.from("invoice_items").insert(rows);
  if (itemsErr) return { error: `Invoice saved but items failed: ${itemsErr.message}` };

  revalidatePath("/admin/invoices");
  revalidatePath("/technician/invoices");
  return { id: updated.id, receipt_no: updated.receipt_no, organization_id: updated.organization_id };
}
