"use server";

// Anonymous ticket submission.
// Runs entirely server-side using the service-role key so we don't have to
// open up broad RLS on the tickets table. The tracking token generated by
// the DB trigger is the only credential the requester needs to check status.

import { createAdminClient } from "@/lib/supabase/admin";

export interface CreateAnonymousInput {
  name: string;
  email: string;
  phone?: string;
  title: string;
  description: string;
  client_id: string;
  tenant_id?: string | null;
  category_id?: string | null;
  priority?: string;
  specific_area?: string | null;
  unit_number?: string | null;
  terms_accepted: boolean;
  photos: { path: string; name: string }[];
}

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export async function createAnonymousTicket(
  input: CreateAnonymousInput
): Promise<{ error?: string; token?: string }> {
  // ------ validation ------
  if (!input.terms_accepted) return { error: "Please accept the terms to continue." };
  if (!input.name?.trim())   return { error: "Please enter your name." };
  if (!EMAIL_RE.test(input.email?.trim() ?? ""))
    return { error: "Please enter a valid email address." };
  if (!input.title?.trim() || input.title.trim().length < 3)
    return { error: "Please enter a short title (min 3 characters)." };
  if (!input.description?.trim()) return { error: "Please describe the problem." };
  if (!input.client_id)           return { error: "Please pick a location." };

  const admin = createAdminClient();

  // Verify the client is active.
  const { data: client } = await admin
    .from("clients")
    .select("id, is_active")
    .eq("id", input.client_id)
    .maybeSingle<{ id: string; is_active: boolean }>();
  if (!client || !client.is_active) {
    return { error: "That location is not accepting tickets right now." };
  }

  // If a tenant was picked, make sure it belongs to that client.
  if (input.tenant_id) {
    const { data: tenant } = await admin
      .from("client_tenants")
      .select("id, client_id, is_active")
      .eq("id", input.tenant_id)
      .maybeSingle<{ id: string; client_id: string; is_active: boolean }>();
    if (!tenant || !tenant.is_active || tenant.client_id !== input.client_id) {
      return { error: "That company isn't valid for the chosen location." };
    }
  }

  // ------ create ticket ------
  const { data: inserted, error } = await admin
    .from("tickets")
    .insert({
      title:            input.title.trim(),
      description:      input.description.trim(),
      client_id:        input.client_id,
      tenant_id:        input.tenant_id ?? null,
      category_id:      input.category_id ?? null,
      priority:         (input.priority as string) || "medium",
      specific_area:    input.specific_area?.trim() || null,
      unit_number:      input.unit_number?.trim() || null,
      status:           "submitted",
      raised_by:        null,
      requester_name:   input.name.trim(),
      requester_email:  input.email.trim().toLowerCase(),
      requester_phone:  input.phone?.trim() || null,
    })
    .select("id, tracking_token")
    .single<{ id: string; tracking_token: string }>();

  if (error || !inserted) {
    return { error: error?.message ?? "Could not submit the ticket." };
  }

  // ------ attachments ------
  const photoRows = input.photos.map((p) => ({
    ticket_id:    inserted.id,
    uploaded_by:  null,
    storage_path: p.path,
    file_name:    p.name || "photo.jpg",
    kind:         "issue_photo" as const,
  }));
  if (photoRows.length) {
    const { error: attErr } = await admin.from("ticket_attachments").insert(photoRows);
    if (attErr) console.error("attachment insert failed:", attErr.message);
  }

  return { token: inserted.tracking_token };
}
